# Generated by Django 5.0.1 on 2024-02-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address2',
        ),
    ]
