# Generated by Django 5.0.1 on 2024-01-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_receipt_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='client_org_number',
            new_name='client_doc_number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='vat_amount',
        ),
    ]
