# Generated by Django 5.0.1 on 2024-01-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_rename_client_org_number_receipt_client_doc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=255),
        ),
    ]
