# Generated by Django 5.0.1 on 2024-01-25 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0004_alter_receipt_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=6, null=True)),
                ('quantity', models.FloatField(default=1.0)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_receipt_items', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='receipt.receipt')),
            ],
        ),
    ]
