# Generated by Django 5.0.1 on 2024-01-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_remove_receiptitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='item_num',
            field=models.IntegerField(default=0),
        ),
    ]
