# Generated by Django 5.0.1 on 2024-01-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0010_alter_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='source_id',
            field=models.IntegerField(default=-1),
        ),
    ]
