# Generated by Django 5.0.1 on 2024-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0012_alter_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='emptyItems',
            field=models.IntegerField(default=0),
        ),
    ]
