# Generated by Django 5.0.1 on 2024-01-28 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0013_receipt_emptyitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='emptyItems',
        ),
        migrations.CreateModel(
            name='EmptyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_empty_items', to='receipt.receipt')),
            ],
        ),
    ]
