# Generated by Django 5.0.1 on 2024-01-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0014_remove_receipt_emptyitems_emptyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='emptyitem',
            name='item_num',
            field=models.IntegerField(default=0),
        ),
    ]
