# Generated by Django 5.0.1 on 2024-02-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0015_emptyitem_item_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='client_address2',
        ),
    ]
