# Generated by Django 5.0.1 on 2024-02-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0016_remove_receipt_client_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
