# Generated by Django 5.0.1 on 2024-02-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0017_receipt_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='client_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
