# Generated by Django 5.0.1 on 2024-07-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0018_alter_receipt_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
