# Generated by Django 5.0.1 on 2024-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='next_receipt_number',
        ),
        migrations.AddField(
            model_name='team',
            name='org_number2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='owner_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
