# Generated by Django 5.0.1 on 2024-01-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_next_receipt_number_team_org_number2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
