# Generated by Django 5.0.1 on 2024-01-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='unit_price',
            new_name='buy_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='net_amount',
            new_name='sell_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
