# Generated by Django 5.0.1 on 2024-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_category_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
