# Generated by Django 5.0.1 on 2024-01-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
