# Generated by Django 5.0.1 on 2024-01-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_sell_price'),
        ('receipt', '0003_rename_client_org_number_receipt_client_doc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='receipt.receipt'),
        ),
    ]
