# Generated by Django 5.0.1 on 2024-02-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_item_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
    ]
